### ISSUE TITLE
mid roll and post roll is not player.

### ISSUE THREAD

**Issue by vishalwebsitetoolbox** [JMVTechnology/Clappr-Ads#1]
window.addEventListener('load', function() {
        var playerElement = document.getElementById("player-wrapper");
        var player = new Clappr.Player({
            source: 'http://clappr.io/highline.mp4',
            baseUrl: '/latest',
            mute: true,
            //height: 360,
            //width: 640,
            plugins: [ClapprAds],
            ads: {
                preRoll: {
                    src: 'http://clappr.io/highline.mp4',
                    skip: true,
                    timeout: 5
                },
                midRoll: {
                    at: 10,
                    src: 'http://clappr.io/highline.mp4',
                    skip: true,
                    timeout: 5
                },
                postRoll: {
                     src: 'http://clappr.io/highline.mp4',
                },
                text: {
                    wait: 'Wait % seconds...',
                    skip: 'Skip Ad >'
                }
            }
        });
        player.attachTo(playerElement);
    });

**Comment by tmaiadev** [comment]
Sorry, I did not understand what you are trying to say. Any problems happening?
